pracaInz/force-app/main/default/objects/Company_Product__c/Company_Product__c.object-meta.xml
<CustomObject>
    <label>Company Product</label>
    <nameField>
        <label>Company Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Company_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Company Products</relationshipLabel>
    <relationshipName>Company_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/fields/Company_Product__c.field-meta.xml
<CustomField>
    <fullName>Company_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Product</label>
    <referenceTo>Company_Product__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/fields/Package_price__c.field-meta.xml
<CustomField>
    <fullName>Package_price__c</fullName>
    <inlineHelpText>Price per package</inlineHelpText>
    <label>Price per package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <businessProcess>Customer</businessProcess>
    <description>Opportunity for Customer</description>
    <label>Customer</label>
</RecordType>

pracaInz/force-app/main/default/objects/Opportunity/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <businessProcess>Supplier</businessProcess>
    <description>Opportunity for Supplier</description>
    <label>Supplier</label>
</RecordType>

pracaInz/force-app/main/default/classes/OpportunityDMN.cls
public with sharing class OpportunityDMN {

    private static final String CUSTOMER = 'Customer';
    private static final String SUPPLIER = 'Supplier';

    public static void createName(List<Opportunity> oppToUpdate) {

        Set<String> accountcsIdSet = new Set<String>();
        Set<String> productsIdSet = new Set<String>();
        Set<String> companyProductsIdSet = new Set<String>();
        Map<String, Product2> productMap;
        Map<String, Company_Product__c> companyProductMap;

        Id customerRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(CUSTOMER).getRecordTypeId();
        Id supplierRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(SUPPLIER).getRecordTypeId();

        for (Opportunity thisOpp : oppToUpdate) {
            accountcsIdSet.add(thisOpp.AccountId);

            if (thisOpp.RecordTypeId == customerRecordTypeId) {
                productsIdSet.add(thisOpp.Product__c);
            }

            if (thisOpp.RecordTypeId == supplierRecordTypeId) {
                companyProductsIdSet.add(thisOpp.Company_Product__c);
            }
        }

        Map<String, Account> accountMap = new Map<String, Account>([SELECT Name FROM Account WHERE Id in: accountcsIdSet]);
        
        if (!productsIdSet.isEmpty()) {
            productMap = new Map<String, Product2>([SELECT Name FROM Product2 WHERE Id in: productsIdSet]);
        }

        if (!accountcsIdSet.isEmpty()) {
            companyProductMap = new Map<String, Company_Product__c>([SELECT Name FROM Company_Product__c WHERE Id in: companyProductsIdSet]);
        }

        for (Opportunity thisOpp : oppToUpdate) {
            String oppName;

            if (thisOpp.RecordTypeId == customerRecordTypeId) {
                oppName = 'BUY ' + productMap.get(thisOpp.Product__c).Name + ' - ' + accountMap.get(thisOpp.AccountId).Name;
            }

            if (thisOpp.RecordTypeId == supplierRecordTypeId) {
                oppName = 'SELL ' + companyProductMap.get(thisOpp.Company_Product__c).Name + ' - ' + accountMap.get(thisOpp.AccountId).Name;
            }

            thisOpp.Name = oppName;
        } 
    }

    public static void verifyName(Map<Id, Opportunity> oldOppMap, Map<Id, Opportunity> newOppMap) {

        List<Opportunity> oppToUpdateNameList = new List<Opportunity>();

        for (Opportunity thisOpp : newOppMap.values()) {
            if (thisOpp.Name != oldOppMap.get(thisOpp.Id).Name) {
                oppToUpdateNameList.add(thisOpp);
            }
        }

        createName(oppToUpdateNameList);
    }

    public static void calculateTotalPrice(List<Opportunity> oppList) {
        for (Opportunity thisOpp : oppList) {
            if (thisOpp.Quantity__c != null && thisOpp.Package_price__c != null)
                thisOpp.Amount = thisOpp.Quantity__c * thisOpp.Package_price__c;
        }
    }
}