pracaInz/force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Customer_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Customer_Relationship__c</fullName>
    <label>Customer Relationship</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Realtionships</valueSetName>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Account_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Supplier_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Relationship__c</fullName>
    <label>Supplier Relationship</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Realtionships</valueSetName>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Company_Product__c/Company_Product__c.object-meta.xml
<CustomObject>
    <label>Company Product</label>
    <nameField>
        <label>Company Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Company_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Company Products</relationshipLabel>
    <relationshipName>Company_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Company_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Company Products</relationshipLabel>
    <relationshipName>Company_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Contact/recordTypes/Driver.recordType-meta.xml
<RecordType>
    <fullName>Driver</fullName>
    <active>true</active>
    <label>Driver</label>
</RecordType>

pracaInz/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Delivery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Pallet_amount__c.field-meta.xml
<CustomField>
    <fullName>Pallet_amount__c</fullName>
    <label>Pallet amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Action taken</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/Delivery_Shipment__c.object-meta.xml
<CustomObject>
    <label>Delivery Shipment</label>
    <nameField>
        <label>Delivery Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Pallet_amount__c.field-meta.xml
<CustomField>
    <fullName>Pallet_amount__c</fullName>
    <label>Pallet amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Total quantity of goods in all pallets</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/fields/Company_Product__c.field-meta.xml
<CustomField>
    <fullName>Company_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Product</label>
    <referenceTo>Company_Product__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/fields/Package_price__c.field-meta.xml
<CustomField>
    <fullName>Package_price__c</fullName>
    <inlineHelpText>Price per package</inlineHelpText>
    <label>Price per package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Opportunity/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <businessProcess>Customer</businessProcess>
    <description>Opportunity for Customer</description>
    <label>Customer</label>
</RecordType>

pracaInz/force-app/main/default/objects/Opportunity/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <businessProcess>Supplier</businessProcess>
    <description>Opportunity for Supplier</description>
    <label>Supplier</label>
</RecordType>

pracaInz/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Destination_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Destination_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Shipments (Destination Warehouse)</relationshipLabel>
    <relationshipName>Destination_Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Driver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Loading_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Loading_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loading Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Loading_Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Max_Pallets__c.field-meta.xml
<CustomField>
    <fullName>Max_Pallets__c</fullName>
    <label>Max Pallets</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
                <default>true</default>
                <label>Planning</label>
            </value>
            <value>
                <fullName>Information provided</fullName>
            </value>
            <value>
                <fullName>Waiting for loading</fullName>
            </value>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>In transport</fullName>
            </value>
            <value>
                <fullName>Awaiting unloading</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Warehouse__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/classes/ShipmentDMN_Test.cls
@isTest
global class ShipmentDMN_Test {

    private static final String CUSTOMER = 'Customer';
    private static final String SUPPLIER = 'Supplier';
    private static final String DRIVER = 'Driver';
    private static final String ACCOUNT_NAME = 'ABSR';
    private static final String ACCOUNT_NAME2 = 'XYZ';
    private static final String CONTACT_NAME = 'Testowy';
    private static final String PRODUCT_NAME = 'Mozzarella';
    private static final String CPRODUCT_NAME = 'Mozzarella Classic';

    @testSetup
    static void dataSetup() {
        Id supplierRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(SUPPLIER).getRecordTypeId();
        Id driverRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(DRIVER).getRecordTypeId();

        Account acc = (Account)TestDataFactory.createSObject('Account', new Map<String, Object>{
            'Name' => ACCOUNT_NAME
        });

        Account acc2 = (Account)TestDataFactory.createSObject('Account', new Map<String, Object>{
            'Name' => ACCOUNT_NAME2
        });

        Contact contact1 = (Contact)TestDataFactory.createSObject('Contact', new Map<String, Object>{
            'LastName' => CONTACT_NAME,
            'AccountId' => acc2.Id,
            'RecordTypeId' => driverRecordTypeId
        });

        Warehouse__c wh = (Warehouse__c)TestDataFactory.createSObject('Warehouse__c', new Map<String, Object>{
            'Account__c' => acc.Id,
            'Name' => 'Testowy Magazyn'
        });

        Warehouse__c wh2 = (Warehouse__c)TestDataFactory.createSObject('Warehouse__c', new Map<String, Object>{
            'Account__c' => acc.Id,
            'Name' => 'Testowy2 Magazyn'
        });

        Product2 prod = (Product2)TestDataFactory.createSObject('Product2', new Map<String, Object>{
            'Name' => PRODUCT_NAME
        });

        Company_Product__c cProd = (Company_Product__c)TestDataFactory.createSObject('Company_Product__c', new Map<String, Object>{
            'Name' => CPRODUCT_NAME,
            'Product__c' => prod.Id,
            'Account__c' => acc.Id
        });

        Opportunity opp1 = (Opportunity)TestDataFactory.createSObject('Opportunity', new Map<String, Object>{
            'Name' => 'x',
            'AccountId' => acc.Id,
            'Company_Product__c' => cProd.Id,
            'StageName' => 'Closed Won',
            'CloseDate' => date.today(),
            'RecordTypeId' => supplierRecordTypeId,
            'Quantity__c' => 1,
            'Package_price__c' => 1
         });

        Contract con1 = (Contract)TestDataFactory.createSObject('Contract', new Map<String, Object>{
            'AccountId' => acc.Id,
            'Opportunity__c' => opp1.Id,
            'Status' => 'Verification'
        });

        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(con1.id);
        Approval.process(req1);
        con1.Status = 'Signed';
        update(con1);

        Delivery_Order__c deliveryOrder = (Delivery_Order__c)TestDataFactory.createSObject('Delivery_Order__c', new Map<String, Object> {
            'Contract__c' => con1.Id,
            'Pallet_amount__c' => 10
        });

        List<Shipment__c> shipmentList = TestDataFactory.createSObjectList('Shipment__c', new Map<String, Object>{
            'Destination_Warehouse__c' => wh.Id,
            'Loading_Warehouse__c' => wh2.Id,
            'Max_Pallets__c' => 100,
            'Status__c' => new List<String>{'Planning', 'Delivered'}
        }, 10);

        List<Id> shipmentListSet = new List<Id>();
        for (Shipment__c thisShipment : shipmentList) {
            shipmentListSet.add(thisShipment.Id);
        }

        List<Delivery_Shipment__c> dsList = TestDataFactory.createSObjectList('Delivery_Shipment__c', new Map<String, Object>{
            'Delivery_Order__c' => deliveryOrder.Id,
            'Shipment__c' => shipmentListSet,
            'Pallet_amount__c' => 1,
            'Quantity__c' => 1
        }, 5);
    }

    @isTest
    static void relationShipIsApproved() {
        Account customerAcc = [SELECT Id FROM Account WHERE Name =: ACCOUNT_NAME LIMIT 1];
        Account supplierAcc = [SELECT Id FROM Account WHERE Name =: ACCOUNT_NAME2 LIMIT 1];
        Contact driver = [SELECT Id FROM Contact WHERE Name =: CONTACT_NAME LIMIT 1];
        
        Account_Relationship__c ar = (Account_Relationship__c)TestDataFactory.createSObject('Account_Relationship__c', new Map<String, Object>{
            'Customer__c' => customerAcc.Id,
            'Customer_Relationship__c' => 'No information',
            'Supplier__c' => supplierAcc.Id,
            'Supplier_Relationship__c' => 'No information'
        });

        List<Shipment__c> shipmentList = [SELECT Driver__c FROM Shipment__c LIMIT 10];

        for (Shipment__c thisShipment : shipmentList) {
            thisShipment.Driver__c = driver.Id;
        }

        Test.startTest();
        update shipmentList;
        Test.stopTest();

        List<Shipment__c> shipmentUpdatedList = [SELECT Driver__c FROM Shipment__c LIMIT 10];
        Boolean isUpdatedCorrect = true;

        for (Shipment__c thisShipment : shipmentUpdatedList) {
            if (thisShipment.Driver__c != driver.Id) {
                isUpdatedCorrect = false;
            }
        } 

        System.assertEquals(true, isUpdatedCorrect, 'Shipments are not updated correct with driver field');
    }

    @isTest
    static void realationShipIsNotApproved() {
        Account customerAcc = [SELECT Id FROM Account WHERE Name =: ACCOUNT_NAME LIMIT 1];
        Account supplierAcc = [SELECT Id FROM Account WHERE Name =: ACCOUNT_NAME2 LIMIT 1];
        Contact driver = [SELECT Id FROM Contact WHERE Name =: CONTACT_NAME LIMIT 1];

        Account_Relationship__c ar = (Account_Relationship__c)TestDataFactory.createSObject('Account_Relationship__c', new Map<String, Object>{
            'Customer__c' => customerAcc.Id,
            'Customer_Relationship__c' => 'Blacklisted',
            'Supplier__c' => supplierAcc.Id,
            'Supplier_Relationship__c' => 'No information'
        });

        List<Shipment__c> shipmentList = [SELECT Driver__c FROM Shipment__c LIMIT 10];

        for (Shipment__c thisShipment : shipmentList) {
            thisShipment.Driver__c = driver.Id;
        }
        Boolean gotError = false;

        Test.startTest();
        try {
            update shipmentList;
        } catch (Exception e) {
            if (e.getMessage().contains(ShipmentDMN.ERROR_MSG)) {
                gotError = true;
            }
        }
        Test.stopTest();

        System.assertEquals(true, gotError, 'No validation shown regards to Account Relationship.');
    }
}