pracaInz/force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Customer_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Customer_Relationship__c</fullName>
    <label>Customer Relationship</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Realtionships</valueSetName>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Account_Relationship__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Account_Relationships1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Contact/recordTypes/Driver.recordType-meta.xml
<RecordType>
    <fullName>Driver</fullName>
    <active>true</active>
    <label>Driver</label>
</RecordType>

pracaInz/force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Delivery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/Delivery_Shipment__c.object-meta.xml
<CustomObject>
    <label>Delivery Shipment</label>
    <nameField>
        <label>Delivery Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Driver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/classes/ShipmentDMN.cls
public with sharing class ShipmentDMN {
    @TestVisible
    private static final String ERROR_MSG = 'The driver is from blacklisted company.';
    private static final String BLACKLISTED = 'Blacklisted';

    public static void validateRelationWithDriver(Map<Id, Shipment__c> shipmentMap) {
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> driversIdSet = new Set<Id>();
        Map<String, Id> customerSupplierIdToShipmentIdMap = new Map<String, Id>();

        for (Shipment__c thisShipment : shipmentMap.values()) {
            driversIdSet.add(thisShipment.Driver__c);
        }

        Map<Id, Contact> driverAccountMap = new Map<Id, Contact>([SELECT AccountId FROM Contact WHERE Id in: driversIdSet]);

        Map<Id, Delivery_Shipment__c> dsMap = new Map<Id, Delivery_Shipment__c>(
            [SELECT Delivery_Order__r.Contract__r.AccountId, Shipment__c FROM Delivery_Shipment__c WHERE Shipment__c in: shipmentMap.keySet()]);

        for (Delivery_Shipment__c thisDS : dsMap.values()) {
            String key = thisDS.Delivery_Order__r.Contract__r.AccountId + '_' + driverAccountMap.get(shipmentMap.get(thisDS.Shipment__c).Driver__c).AccountId;
            customerSupplierIdToShipmentIdMap.put(key, thisDS.Shipment__c);
        }
            
        for (Delivery_Shipment__c thisDs : dsMap.values()) {
            accountIdSet.add(thisDs.Delivery_Order__r.Contract__r.AccountId);
        }

        List<Account_Relationship__c> arList = 
            [SELECT Customer__c, Supplier__c FROM Account_Relationship__c WHERE Customer__c in: accountIdSet AND Customer_Relationship__c =: BLACKLISTED];

        if (arList.size() > 0) {
            for (Account_Relationship__c thisAR : arList) {
                String key = thisAR.Customer__c + '_' + thisAR.Supplier__c;
                if (customerSupplierIdToShipmentIdMap.containsKey(key)) {
                    shipmentMap.get(customerSupplierIdToShipmentIdMap.get(key)).addError(ERROR_MSG);
                } 
            }
        }
    }
}