pracaInz/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Destination_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Destination_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Shipments (Destination Warehouse)</relationshipLabel>
    <relationshipName>Destination_Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Driver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Loading_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Loading_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loading Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Loading_Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Warehouse__c/fields/geoLocation__c.field-meta.xml
<CustomField>
    <fullName>geoLocation__c</fullName>
    <label>geoLocation</label>
    <scale>5</scale>
    <type>Location</type>
</CustomField>

pracaInz/force-app/main/default/classes/ShipmentTRH.cls
public with sharing class ShipmentTRH extends TriggerHandler{

    public override void afterInsert() {
        Set<Id> shipmentIdSet = new Set<Id>();
        Map<Id, Shipment__c> shipmentMapToValidateDriver = new Map<Id, Shipment__c>();

        for (Shipment__c thisShipment : (List<Shipment__c>)Trigger.new) {
            if (thisShipment.Driver__c != null) {
                shipmentMapToValidateDriver.put(thisShipment.Id, thisShipment);
            }
        }

        if (shipmentMapToValidateDriver.size() > 0 ) {
            ShipmentDMN.validateRelationWithDriver(shipmentMapToValidateDriver);
        }

        for (Shipment__c thisShipment : (List<Shipment__c>)Trigger.new) {
            shipmentIdSet.add(thisShipment.Id);
        }

        Map<Id, Shipment__c> shipmentMap = new Map<Id, Shipment__c>(
            [SELECT Id, Destination_Warehouse__r.geoLocation__c, Loading_Warehouse__r.geoLocation__c 
            FROM Shipment__c WHERE Id in: shipmentIdSet]);

        for (Id shipmentId : shipmentMap.keySet()) {
            if (shipmentMap.get(shipmentId).Destination_Warehouse__r.geoLocation__c != null && shipmentMap.get(shipmentId).Loading_Warehouse__r.geoLocation__c != null) {
                TomTomCalloutHandler.getRouteDetails(shipmentId);
            }
        }
    }

    public override void afterUpdate() {
        Map<Id, Shipment__c> shipmentMapToValidateDriver = new Map<Id, Shipment__c>();

        for (Shipment__c thisShipment : (List<Shipment__c>)Trigger.new) {
            if (thisShipment.Driver__c != null) {
                shipmentMapToValidateDriver.put(thisShipment.Id, thisShipment);
            }
        }

        if (shipmentMapToValidateDriver.size() > 0 ) {
            ShipmentDMN.validateRelationWithDriver(shipmentMapToValidateDriver);
        }
    }
}