pracaInz/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Delivery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Delivery Orders</relationshipLabel>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Pallet_amount__c.field-meta.xml
<CustomField>
    <fullName>Pallet_amount__c</fullName>
    <label>Pallet amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Action taken</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/Delivery_Shipment__c.object-meta.xml
<CustomObject>
    <label>Delivery Shipment</label>
    <nameField>
        <label>Delivery Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Pallet_amount__c.field-meta.xml
<CustomField>
    <fullName>Pallet_amount__c</fullName>
    <label>Pallet amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Total quantity of goods in all pallets</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/Delivery_Stop__c.object-meta.xml
<CustomObject>
    <label>Delivery Stop</label>
    <nameField>
        <label>Delivery Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Stops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Stops</relationshipLabel>
    <relationshipName>Delivery_Stops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Stop_Order__c.field-meta.xml
<CustomField>
    <fullName>Stop_Order__c</fullName>
    <label>Stop Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Delivery Stops</relationshipLabel>
    <relationshipName>Delivery_Stops</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Destination_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Destination_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Shipments (Destination Warehouse)</relationshipLabel>
    <relationshipName>Destination_Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Loading_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Loading_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loading Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Loading_Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
                <default>true</default>
                <label>Planning</label>
            </value>
            <value>
                <fullName>Information provided</fullName>
            </value>
            <value>
                <fullName>Waiting for loading</fullName>
            </value>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>In transport</fullName>
            </value>
            <value>
                <fullName>Awaiting unloading</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/classes/BatchSummaryController.cls
public with sharing class BatchSummaryController {
    private final static Set<String> TANSPORTATION_STATUSES = new Set<String> {'Waiting for loading', 'Loading', 'In transport', 'Awaiting unloading', 'Unloading'};  
    private final static String DELIVERED_STATUS = 'Delivered';
    private final static String WAREHOUSE = 'Warehouse';  
    private final static String SHIPMENT = 'Shipment';  
    private final static String SHIPMENT_STATUS = 'Shipment_Status';  
    private final static String PALLETS_AMOUNT = 'Pallets_Amount';  
    private final static String QUANTITY = 'Quantity';  
    private final static String ID = 'Id';  

    @AuraEnabled(cacheable=true)
    public static List<Object> getListToDisplay(Id deliveryOrderId) {
        List<Object> objectList = new List<Object>();
        Delivery_Order__c deliveryOrder = [SELECT Id, Pallet_amount__c, Contract__r.Opportunity__r.Quantity__c,
            (SELECT Id, Pallet_amount__c, Quantity__c, Shipment__r.Name, Shipment__r.Status__c, Shipment__r.Destination_Warehouse__r.Name, 
            Shipment__r.Loading_Warehouse__r.Name, Shipment__r.Destination_Warehouse__r.Id, Shipment__r.Loading_Warehouse__r.Id 
            FROM Delivery_Shipments__r), (SELECT Warehouse__r.Id, Warehouse__r.Name FROM Delivery_Stops__r WHERE Stop_Order__c = 1 LIMIT 1) FROM Delivery_Order__c WHERE Id =: deliveryOrderId WITH SECURITY_ENFORCED LIMIT 1];

        final Double maxPalletAmount = deliveryOrder.Pallet_amount__c;
        final Double maxQuantity = deliveryOrder.Contract__r.Opportunity__r.Quantity__c;

        Map<Id, Double> palletQuantityAtWarehouse = new Map<Id, Double>{deliveryOrder.Delivery_Stops__r[0].Warehouse__r.Id => maxPalletAmount};
        Map<Id, Double> goodsQuantityAtWarehouse = new Map<Id, Double>{deliveryOrder.Delivery_Stops__r[0].Warehouse__r.Id => maxQuantity};
        Map<Id, String> warehouseIdToNameMap = new Map<Id, String>{deliveryOrder.Delivery_Stops__r[0].Warehouse__r.Id => deliveryOrder.Delivery_Stops__r[0].Warehouse__r.Name};

        if (((List<Delivery_Shipment__c>)deliveryOrder.Delivery_Shipments__r).size() > 0) { 
            for (Delivery_Shipment__c thisDS : (List<Delivery_Shipment__c>)deliveryOrder.Delivery_Shipments__r) { 
                if (TANSPORTATION_STATUSES.contains(thisDS.Shipment__r.Status__c)) {
                    if (!palletQuantityAtWarehouse.containsKey(thisDS.Shipment__r.Loading_Warehouse__r.Id)) {
                        palletQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, thisDS.Pallet_amount__c * -1);
                        goodsQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, thisDS.Quantity__c * -1);
                        warehouseIdToNameMap.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, thisDS.Shipment__r.Loading_Warehouse__r.Name);
                    } else {
                        Double newPalletQuantity = palletQuantityAtWarehouse.get(thisDS.Shipment__r.Loading_Warehouse__r.Id) - thisDS.Pallet_amount__c;
                        Double newGoodsQuantity = goodsQuantityAtWarehouse.get(thisDS.Shipment__r.Loading_Warehouse__r.Id) - thisDS.Quantity__c;
                        palletQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, newPalletQuantity);
                        goodsQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, newGoodsQuantity);
                    }

                    Map<String, Object> recordToDisplay = new Map<String, Object>();
                    recordToDisplay.put(SHIPMENT, thisDS.Shipment__r.Name);
                    recordToDisplay.put(SHIPMENT_STATUS, thisDS.Shipment__r.Status__c);
                    recordToDisplay.put(PALLETS_AMOUNT, thisDS.Pallet_amount__c);
                    recordToDisplay.put(QUANTITY, thisDS.Quantity__c);
                    recordToDisplay.put(ID, thisDS.Id);
                    objectList.add(recordToDisplay);
                }
                if (DELIVERED_STATUS.contains(thisDS.Shipment__r.Status__c)) {
                    if (!palletQuantityAtWarehouse.containsKey(thisDS.Shipment__r.Loading_Warehouse__r.Id)) {
                        palletQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, thisDS.Pallet_amount__c * -1);
                        goodsQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, thisDS.Quantity__c * -1);
                        warehouseIdToNameMap.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, thisDS.Shipment__r.Loading_Warehouse__r.Name);
                    } else {
                        Double newPalletQuantity = palletQuantityAtWarehouse.get(thisDS.Shipment__r.Loading_Warehouse__r.Id) - thisDS.Pallet_amount__c;
                        Double newGoodsQuantity = goodsQuantityAtWarehouse.get(thisDS.Shipment__r.Loading_Warehouse__r.Id) - thisDS.Quantity__c;
                        palletQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, newPalletQuantity);
                        goodsQuantityAtWarehouse.put(thisDS.Shipment__r.Loading_Warehouse__r.Id, newGoodsQuantity);
                    }

                    if (!palletQuantityAtWarehouse.containsKey(thisDS.Shipment__r.Destination_Warehouse__r.Id)) {
                        palletQuantityAtWarehouse.put(thisDS.Shipment__r.Destination_Warehouse__r.Id, thisDS.Pallet_amount__c);
                        warehouseIdToNameMap.put(thisDS.Shipment__r.Destination_Warehouse__r.Id, thisDS.Shipment__r.Destination_Warehouse__r.Name);
                        goodsQuantityAtWarehouse.put(thisDS.Shipment__r.Destination_Warehouse__r.Id, thisDS.Quantity__c);
                    } else {
                        Double newPalletQuantity = palletQuantityAtWarehouse.get(thisDS.Shipment__r.Destination_Warehouse__r.Id) + thisDS.Pallet_amount__c;
                        Double newGoodsQuantity = goodsQuantityAtWarehouse.get(thisDS.Shipment__r.Destination_Warehouse__r.Id) + thisDS.Quantity__c;
                        palletQuantityAtWarehouse.put(thisDS.Shipment__r.Destination_Warehouse__r.Id, newPalletQuantity);
                        goodsQuantityAtWarehouse.put(thisDS.Shipment__r.Destination_Warehouse__r.Id, newGoodsQuantity);
                    }
                }
            }

            for (Id warehouseId: palletQuantityAtWarehouse.keySet()) {
                if (palletQuantityAtWarehouse.get(warehouseId) > 0) {
                    Map<String, Object> recordToDisplay = new Map<String, Object>();
                    recordToDisplay.put(WAREHOUSE, warehouseIdToNameMap.get(warehouseId));
                    recordToDisplay.put(PALLETS_AMOUNT, palletQuantityAtWarehouse.get(warehouseId));
                    recordToDisplay.put(QUANTITY, goodsQuantityAtWarehouse.get(warehouseId));
                    recordToDisplay.put(ID, warehouseId);
                    objectList.add(recordToDisplay);
                }
            }
        }
        else {
            Map<String, Object> recordToDisplay = new Map<String, Object>();
            recordToDisplay.put(WAREHOUSE, deliveryOrder.Delivery_Stops__r[0].Warehouse__r.Name);
            recordToDisplay.put(PALLETS_AMOUNT, maxPalletAmount);
            recordToDisplay.put(QUANTITY, maxQuantity);
            objectList.add(recordToDisplay);
        }

        return objectList;
    }
}