pracaInz/force-app/main/default/objects/Delivery_Shipment__c/Delivery_Shipment__c.object-meta.xml
<CustomObject>
    <label>Delivery Shipment</label>
    <nameField>
        <label>Delivery Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Pallet_amount__c.field-meta.xml
<CustomField>
    <fullName>Pallet_amount__c</fullName>
    <label>Pallet amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Total quantity of goods in all pallets</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Proof_of_Delivery__c/Proof_of_Delivery__c.object-meta.xml
<CustomObject>
    <label>Proof of Delivery</label>
    <nameField>
        <displayFormat>PoD-{0000}</displayFormat>
        <label>Proof of Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs of Delivery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Proof_of_Delivery__c/fields/Delivered_quantity__c.field-meta.xml
<CustomField>
    <fullName>Delivered_quantity__c</fullName>
    <inlineHelpText>Total quantity of goods that are delivered.</inlineHelpText>
    <label>Delivered quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Proof_of_Delivery__c/fields/Delivery_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Shipment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Shipment</label>
    <referenceTo>Delivery_Shipment__c</referenceTo>
    <relationshipLabel>Proofs of Delivery</relationshipLabel>
    <relationshipName>Proofs_of_Delivery</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Proof_of_Delivery__c/fields/Pallet_Delivered_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Delivered_Amount__c</fullName>
    <inlineHelpText>Total number of amount that are delivered.</inlineHelpText>
    <label>Pallet delivered amount</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
                <default>true</default>
                <label>Planning</label>
            </value>
            <value>
                <fullName>Information provided</fullName>
            </value>
            <value>
                <fullName>Waiting for loading</fullName>
            </value>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>In transport</fullName>
            </value>
            <value>
                <fullName>Awaiting unloading</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pracaInz/force-app/main/default/classes/ProofOfDeliveryDMN.cls
public with sharing class ProofOfDeliveryDMN {
    @TestVisible
    private static final String ERROR_MSG_1 = 'Delivered Quantity is more than quantity on related Delivery Shipment!';
    @TestVisible
    private static final String ERROR_MSG_2 = 'Pallet Pallet Ammount is more than Pallet Ammount on related Delivery Shipment!';
    @TestVisible
    private static final String ERROR_MSG_3 = 'Shipment status related to Delivery Shipment is not "delivered"';
    private static final String DELIVERED_STATUS = 'Delivered';

    public static void validateQuantities(List<Proof_of_Delivery__c> inputList) {
        Set<Id> deliveryShipmentIdSet = new Set<Id>();
        
        for (Proof_of_Delivery__c thisProof : inputList) {
            deliveryShipmentIdSet.add(thisProof.Delivery_Shipment__c);
        }

        Map<Id, Delivery_Shipment__c> dsMap = new Map<Id, Delivery_Shipment__c>(
            [SELECT Pallet_amount__c, Quantity__c FROM Delivery_Shipment__c WHERE Id in: deliveryShipmentIdSet]);

        for (Proof_of_Delivery__c thisProof : inputList) {
            if (thisProof.Delivered_quantity__c > dsMap.get(thisProof.Delivery_Shipment__c).Quantity__c) {
                thisProof.Delivered_quantity__c.addError(ERROR_MSG_1);
            }
            if (thisProof.Pallet_Delivered_Amount__c > dsMap.get(thisProof.Delivery_Shipment__c).Pallet_amount__c) {
                thisProof.Pallet_Delivered_Amount__c.addError(ERROR_MSG_2);
            }
        }
    }

    public static void validateShipmentStatus(List<Proof_of_Delivery__c> inputList) {
        Set<Id> deliveryShipmentIdSet = new Set<Id>();
        
        for (Proof_of_Delivery__c thisProof : inputList) {
            deliveryShipmentIdSet.add(thisProof.Delivery_Shipment__c);
        }

        Map<Id, Delivery_Shipment__c> dsMap = new Map<Id, Delivery_Shipment__c>(
            [SELECT Id, Shipment__r.Status__c FROM Delivery_Shipment__c]);
        
        for (Proof_of_Delivery__c thisProof : inputList) {
            if (dsMap.get(thisProof.Delivery_Shipment__c).Shipment__r.Status__c != DELIVERED_STATUS) {
                thisProof.Delivery_Shipment__c.addError(ERROR_MSG_3);
            }
        }
    }
}