pracaInz/force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Delivery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/Delivery_Stop__c.object-meta.xml
<CustomObject>
    <label>Delivery Stop</label>
    <nameField>
        <label>Delivery Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Stops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Stops</relationshipLabel>
    <relationshipName>Delivery_Stops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Stop_Order__c.field-meta.xml
<CustomField>
    <fullName>Stop_Order__c</fullName>
    <label>Stop Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Delivery Stops</relationshipLabel>
    <relationshipName>Delivery_Stops</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/classes/DeliveryStopDMN.cls
public with sharing class DeliveryStopDMN {
    public static void setUpStopOrder(Map<Id, List<Delivery_Stop__c>> deliveryOrderIdToDeliveryStopListMap) {

        Map<Id, Delivery_Order__c> deliveryOrderMap = new Map<Id, Delivery_Order__c>(
            [SELECT Id, (SELECT Id FROM Delivery_Stops__r) FROM Delivery_Order__c 
                WHERE Id in: deliveryOrderIdToDeliveryStopListMap.keySet()]);

        for (Id thisDSId : deliveryOrderIdToDeliveryStopListMap.keySet()) {

            Integer stopOrder = deliveryOrderMap.get(thisDSId).Delivery_Stops__r.size();

            for (Delivery_Stop__c thisDS : deliveryOrderIdToDeliveryStopListMap.get(thisDSId)) {
                stopOrder++;
                thisDs.Stop_Order__c = stopOrder;
            }
        }
    }

    public static void createName (List<Delivery_Stop__c> dsList) {
        Set<Id> warehouseIdSet = new Set<Id>();
        
        for (Delivery_Stop__c thisDS : dsList) {
            warehouseIdSet.add(thisDS.Warehouse__c);
        }

        Map<Id, Warehouse__c> warehouseMap = new Map<Id, Warehouse__c>([SELECT Name FROM Warehouse__c WHERE Id in: warehouseIdSet]);

        for (Delivery_Stop__c thisDS : dsList) {
            thisDS.Name = warehouseMap.get(thisDS.Warehouse__c).Name + ' DS';
        }
    } 

    public static void reorderStopOrders(List<Delivery_Stop__c> toDeleteList) {
        List<Delivery_Stop__c> deliveryOrdersToUpdate = new List<Delivery_Stop__c>();
        Set<Id> deliveryOrderIdSet = new Set<Id>();

        for (Delivery_Stop__c thisDS : toDeleteList) {
            deliveryOrderIdSet.add(thisDS.Delivery_Order__c);
        }

        List<Delivery_Order__c> deliveryOrderList = [SELECT Id, (SELECT Id, Stop_Order__c FROM Delivery_Stops__r ORDER BY Stop_Order__c ASC) 
                                                        FROM Delivery_Order__c WHERE Id in: deliveryOrderIdSet];

        for (Delivery_Order__c thisDO : deliveryOrderList) {
            if (thisDO.Delivery_Stops__r.size() > 0) {
                Integer stopOrderCounter = 1;
    
                for (Delivery_Stop__c thisDS : thisDO.Delivery_Stops__r) {
                    thisDS.Stop_Order__c = stopOrderCounter;
                    deliveryOrdersToUpdate.add(thisDS);
                    stopOrderCounter++;
                }
            }
        }

        if (deliveryOrdersToUpdate.size() > 0) {
            update(deliveryOrdersToUpdate);
        }
    }
}