pracaInz/force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Delivery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/Delivery_Shipment__c.object-meta.xml
<CustomObject>
    <label>Delivery Shipment</label>
    <nameField>
        <label>Delivery Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Delivery_Shipment__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Delivery Shipments</relationshipLabel>
    <relationshipName>Delivery_Shipments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/objects/Proof_of_Delivery__c/Proof_of_Delivery__c.object-meta.xml
<CustomObject>
    <label>Proof of Delivery</label>
    <nameField>
        <displayFormat>PoD-{0000}</displayFormat>
        <label>Proof of Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proofs of Delivery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Proof_of_Delivery__c/fields/Delivery_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Shipment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Shipment</label>
    <referenceTo>Delivery_Shipment__c</referenceTo>
    <relationshipLabel>Proofs of Delivery</relationshipLabel>
    <relationshipName>Proofs_of_Delivery</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

pracaInz/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/classes/DeliveryShipmentDMN.cls
public with sharing class DeliveryShipmentDMN {
    @TestVisible
    private static final String ERROR_MSG = 'Each Delivery Shipment may only has one Proof of Delivery record.';

    public static void createName(List<Delivery_Shipment__c> dsList) {
        Set<Id> deliveryOrderIdsSet = new Set<Id>();
        Set<Id> shipmentIdsSet = new Set<Id>();

        for (Delivery_Shipment__c thisDS : dsList) {
            deliveryOrderIdsSet.add(thisDS.Delivery_Order__c);
            shipmentIdsSet.add(thisDS.Shipment__c);
        }

        Map<Id, Shipment__c> shipmentsMap = new Map<Id, Shipment__c>([SELECT Name FROM Shipment__c WHERE Id in: shipmentIdsSet]);
        Map<Id, Delivery_Order__c> deliveryOrdersMap = new Map<Id, Delivery_Order__c>([SELECT Name FROM Delivery_Order__c WHERE Id in: deliveryOrderIdsSet]);

        for (Delivery_Shipment__c thisDS : dsList) {
            thisDS.Name = deliveryOrdersMap.get(thisDS.Delivery_Order__c).Name + '-' + shipmentsMap.get(thisDS.Shipment__c).Name;
        }
    }

    public static void validateMaxNumberProofOfDelivery(List<Proof_of_Delivery__c> inputList) {
        Set<Id> deliveryShipmentId = new Set<Id>();

        for (Proof_of_Delivery__c thisProof : inputList) {
            deliveryShipmentId.add(thisProof.Delivery_Shipment__c);
        }

        Map<Id, Delivery_Shipment__c> dsMap = new Map<Id, Delivery_Shipment__c>(
            [SELECT Id, (SELECT Id FROM Proofs_of_Delivery__r) FROM Delivery_Shipment__c]);

        for (Proof_of_Delivery__c thisProof : inputList) {
            if (dsMap.get(thisProof.Delivery_Shipment__c).Proofs_of_Delivery__r.size() > 0) {
                thisProof.Delivery_Shipment__c.addError(ERROR_MSG);
            }
        }
    }
}