pracaInz/force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>Delivery Order</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Delivery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/Delivery_Stop__c.object-meta.xml
<CustomObject>
    <label>Delivery Stop</label>
    <nameField>
        <label>Delivery Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Stops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pracaInz/force-app/main/default/objects/Delivery_Stop__c/fields/Delivery_Order__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Order__c</fullName>
    <label>Delivery Order</label>
    <referenceTo>Delivery_Order__c</referenceTo>
    <relationshipLabel>Delivery Stops</relationshipLabel>
    <relationshipName>Delivery_Stops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

pracaInz/force-app/main/default/classes/DeliveryStopTRH.cls
public with sharing class DeliveryStopTRH extends TriggerHandler{
    
    public override void beforeInsert() {
        Map<Id, List<Delivery_Stop__c>> deliveryOrderToDeliveryStopListMap = new Map<Id, List<Delivery_Stop__c>>();

        for (Delivery_Stop__c thisDS : (List<Delivery_Stop__c>)Trigger.new) {

            if (!deliveryOrderToDeliveryStopListMap.containsKey(thisDS.Delivery_Order__c)) {
                List<Delivery_Stop__c> dsList = new List<Delivery_Stop__c>();
                dsList.add(thisDS);
                deliveryOrderToDeliveryStopListMap.put(thisDS.Delivery_Order__c, dsList);
            }
            else {
                List<Delivery_Stop__c> dsList = deliveryOrderToDeliveryStopListMap.get(thisDS.Delivery_Order__c);
                dsList.add(thisDS);
                deliveryOrderToDeliveryStopListMap.put(thisDS.Delivery_Order__c, dsList);
            }            
        }

        DeliveryStopDMN.setUpStopOrder(deliveryOrderToDeliveryStopListMap);
        DeliveryStopDMN.createName((List<Delivery_Stop__c>)Trigger.new);
    } 
}